### PR TITLE
Update Formats

### PR DESCRIPTION
**Pull request by ghost**
Copied directly from spacialgaze lol

### CODE REVIEW

**Comment by HoeenCoder** [comment]
You should update from SG instead of pulling just the formats file tbh, otherwise a mess can ensue

**Comment by HoeenCoder** [comment]
I can start a PR for that

**Comment by DesoGit** [comment]
Hoeen, that would be nice

**Comment by HoeenCoder** [comment]
nvrm the PR needs to be done manually

**Comment by ghost** [comment]
Oh ok, sorry about that

**Pull request closed without merging**
